### PR TITLE
PR for 12766 Better message for "creating session with W3C"  

### PR DESCRIPTION
**Pull request by Siddh010**
PR for PR for 12766 Better message for "creating session with W3C"

### CODE REVIEW

**Comment by dpgraham** [comment]
@Siddh010 can you sign the CLA? https://cla.js.foundation/appium/appium-base-driver?pullRequest=329

**Comment by KazuCocoa** [comment]
link: https://github.com/appium/appium/issues/12766

**Comment by Siddh010** [comment]
I have sign in CLA

**Comment by KazuCocoa** [comment]
What email did you set on your git commit preference?
The signing email should be the same as it.
Or you can revert and commit again with your email, https://github.com/appium/appium-base-driver/pull/329#issuecomment-501961527

**Comment by Siddh010** [comment]
Closing this PR as it is a duplicate of [PR 331](https://github.com/appium/appium-base-driver/pull/331)

**Pull request closed without merging**
