### PR TITLE
Added route for setDeviceTime

### PR DESCRIPTION
**Pull request by anthonypdawson**
Implementing setting device time for the Android platform across this repo, appium-android-driver and python-client

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
This endpoint won't work on iOS anyway. Also, it makes less sense on other platforms. I'd rather add as a apart of `mobile: ` interface for Android only.

**Comment by mykola-mokhnach** [comment]
@jlipps @imurchie What do you think?

**Comment by mykola-mokhnach** [comment]
GET is ok, since it more or less available everywhere, but setTime is blocked on many platforms

**Comment by imurchie** [comment]
I agree this could be a setting, or a desired capability even. What is the use case for changing the device date/time mid-session?

**Comment by mykola-mokhnach** [comment]
This PR has been superseeded by https://github.com/mykola-mokhnach/appium/blob/9f36377d7ba47d7b55ae4d98577872917e6f083d/docs/en/writing-running-appium/android/android-shell.md

**Pull request closed without merging**
