### PR TITLE
fix the smbfs path

### PR DESCRIPTION
**Pull request by wei-gu**

### CODE REVIEW

**Comment by imurchie** [comment]
@wei-gu Can you check your git configuration? You don't seem to be committing with a username associated with a github account.

**Comment by imurchie** [comment]
Bringing @yaphatak into the conversation, since he wrote the original code and might know more.

**Comment by wei-gu** [comment]
@yaphatak left Microsoft and I took the work from him. For now, we are using workaround to make it work with: 
"**windowsShareUserName**":"**//**domain;name"
to add extra "**//**"

**Comment by jlipps** [comment]
ok, sounds good. looks like all that's left is fixing your git config and re-pushing

**Comment by wei-gu** [comment]
just did and create another PR

**Pull request closed without merging**
