### PR TITLE
adding fingerprint to routes

### PR DESCRIPTION
**Pull request by alizelzele**
requires : [adding fingerprint command](https://github.com/appium/appium-android-driver/pull/181) to work.

### CODE REVIEW

**Comment by alizelzele** [comment]
it will solve the issue [Requires fingerprint supporting](https://github.com/appium/appium/issues/6782)

**Comment by imurchie** [comment]
Please run the unit tests locally (using `gulp once`). Changes to the protocol require changing a hash value in one of the tests.

Otherwise, this seems reasonable. Thanks!

**Comment by alizelzele** [comment]
@imurchie I was not able to `npm install` at that moment. (google is filtered here !! ) 😄 
Sorry for pushing the code without running tests.

**Comment by imurchie** [comment]
Thanks!

**Comment by imurchie** [comment]
Published in `appium-base-driver@2.0.15`.

**Pull request merged**
