### PR TITLE
pull other packages into base-driver

### PR DESCRIPTION
**Pull request by jlipps**
according to our dearchitecture plan.

This also involved updating readmes, writing some tests, using new lodash, etc...

Given the many changes, if you're curious, might want to look commit-by-commit

### CODE REVIEW

**Comment by jlipps** [comment]
hmm, running the jsonwp-proxy tests on their own in travis to see if it's something that might have changed in travis.

**Comment by jlipps** [comment]
ahh it's because we weren't running e2e tests for jsonwp-proxy before

**Comment by jlipps** [comment]
ok @imurchie once this passes build it should be ready to merge assuming we're not intending to make any minor changes to base-driver right now, or any changes at all to the mjsonwp, jwproxy, jwstatus, or express packages! (until we go through and update the deps for all packages which used to depend on them)

**Comment by imurchie** [comment]
Cool! I look forward to getting that all updated!

**Comment by imurchie** [comment]
👍

**Pull request merged**
