### PR TITLE
adding rect routes

### PR DESCRIPTION
**Pull request by wfanforever**
@jlipps @imurchie @rafael-chavez 

Adding a new routes to match wda: 
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DriverCommand.java#L83

WDA:
https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L46

new spec:
https://w3c.github.io/webdriver/webdriver-spec.html#get-element-rect

### CODE REVIEW

**Comment by imurchie** [comment]
This route should go down in the bottom section (https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L396-L423) where we have begun to add W3C spec routes.

**Comment by wfanforever** [comment]
@imurchie I have updated the PR to move it to the bottom. :)

**Comment by jlipps** [comment]
👍

**Comment by imurchie** [comment]
Excellent! Thanks for this!

**Pull request merged**
