### PR TITLE
Adding get swipe options

### PR DESCRIPTION
**Pull request by moizjv**

### CODE REVIEW

**Comment by sebv** [comment]
This should probbably live in a gesture.js command file.

**Comment by moizjv** [comment]
@jlipps and I had a talk about it. It is more of a helper function not a command

**Comment by sebv** [comment]
We should devise a way so that everything doesn't ends up in driver.js and the code is sort of functionally organized.

**Comment by jlipps** [comment]
LGTM. @sebv it's either this or we make a new helpers file and add it to the prototype. either way, but so far this is the only thing like it for android driver so i suggested putting it on the driver

**Comment by sebv** [comment]
It's similar to https://github.com/appium/appium-android-driver/blob/master/lib/commands/find.js#L11, we already have helpers in command file for this. Anyway not too important, we can reformat later.

**Comment by jlipps** [comment]
yes, it's exactly the same as that, we just didn't want to make a new file immediately. but i agree it can be factored out easily. NBD.

**Comment by moizjv** [comment]
Merging it, will refactor later if needed

**Pull request merged**
