### PR TITLE
add isArray to cap validation strategies

### PR DESCRIPTION
**Pull request by jlipps**
also add a log line i found helpful

### CODE REVIEW

**Comment by jlipps** [comment]
travis failure is due to what looks like an unrelated flake. i also ran into this locally apart from this PR. how do we have flakes in our unit tests?

**Comment by mykola-mokhnach** [comment]
There is one unstable test...

**Comment by jlipps** [comment]
i'll try to fix the test in another PR, not sure why it's not working

**Comment by jlipps** [comment]
published in 3.15.5. test hopefully fixed in https://github.com/appium/appium-base-driver/pull/315

**Pull request merged**
