### PR TITLE
Add new endpoints

### PR DESCRIPTION
**Pull request by vrunoa**
Adding endpoints for the new methods we're adding on android emulators.

### CODE REVIEW

**Comment by vrunoa** [comment]
thanks @imurchie. 
Once the emu methods are merge on appium-android-driver we can merge this one.

**Comment by imurchie** [comment]
The order should not matter. Any method here that is not implemented on the driver will just return a "not yet implemented" error automatically.

**Comment by vrunoa** [comment]
Oh didnt knew that. Cool.

**Comment by imurchie** [comment]
That's how we handle things like the fact that the iOS drivers are not going to implement these methods.

Just for interest's sake, the code is here: https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/driver.js#L182-L184

**Comment by imurchie** [comment]
Published in `appium-base-driver@2.12.0`.

**Pull request merged**
