### PR TITLE
Added YouiEngine to the list of automationName

### PR DESCRIPTION
**Pull request by simongranger**
Goes with this PR: https://github.com/appium/appium/pull/6215

### CODE REVIEW

**Comment by jlipps** [comment]
👍

**Comment by imurchie** [comment]
Looks good to me. I am fine with this getting in before the rest is there (no harm to allowing it).

**Comment by imurchie** [comment]
Plus it reminds me that I need to add the xcuitest entry here ;)

**Comment by jlipps** [comment]
published as 2.0.6

**Pull request merged**
