### PR TITLE
feat: Remove wd hub prefix

### PR DESCRIPTION
**Pull request by KazuCocoa**
https://github.com/appium/appium/projects/2#card-43906187
We want to remove `/wd/hub` default base path.

--

Haven't tested and tweaked well yet, but did the task intend to do like this? @jlipps 
(This PR is to 2.0 branch)

### CODE REVIEW

**Comment by jlipps** [comment]
@KazuCocoa i think we should merge this into the 2.0 branch of base driver and publish as `@beta` or `@next`, sound good?

**Comment by jlipps** [comment]
> we need to update the default for the -ap arg on the main server too.

actually we don't need to do this as long as we update the exported DEFAULT_BASE_PATH in this PR

**Comment by KazuCocoa** [comment]
Yeah, could be 🆗

**Comment by jlipps** [comment]
@KazuCocoa can you remove the WIP tag so we can merge?

**Comment by KazuCocoa** [comment]
removed ✅

**Comment by jlipps** [comment]
ok merged and published as beta!

**Pull request merged**
