### PR TITLE
fix: Return proper responses to unexpected errors

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
All clients expect responses to be returned as valid json objects and throw exceptions in case of plain text: https://gist.github.com/TransmitTomerDavid/31132cd2ea3ce3c4514e24494ad8f504

### CODE REVIEW

**Review by jlipps — APPROVED** [review]
LGTM, but pretty sure this could break JSONWP client support?

**Comment by mykola-mokhnach** [comment]
@jlipps According to what I see in clients all of them are only expecting JSON responses.

**Comment by mykola-mokhnach** [comment]
@jlipps Could you also help fixing https://travis-ci.org/github/appium/appium-base-driver/jobs/725344616#L1804 (perhaps in the other PR). I have a feeling these tests were broken before.

**Comment by jlipps** [comment]
sure, will take a look

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
