### PR TITLE
Add missing error codes

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This should fix https://github.com/appium/appium/issues/10286, since selenium clients such as java one decide which exception should be thrown based on the standard codes/descriptions.

### CODE REVIEW

**Comment by dpgraham** [comment]
* Made some comments. A bunch of the errors are 404 that should be 400 (see https://www.w3.org/TR/webdriver/ for reference)
* You don't need to add the `w3cStatus()` method for 400, 400 is the default.
* Some of these commands aren't W3C commands, are you basically just taking old MJSONWP commands and making them compatible with W3C (which I'm okay with)?

**Comment by mykola-mokhnach** [comment]
> Made some comments. A bunch of the errors are 404 that should be 400 (see https://www.w3.org/TR/webdriver/ for reference)

It seems like there is also a bug in Selenium implementation. I'll raise a bug to them.

> You don't need to add the w3cStatus() method for 400, 400 is the default.

I'd rather keep it (`explicit is better than implicit`).

> Some of these commands aren't W3C commands, are you basically just taking old MJSONWP commands and making them compatible with W3C (which I'm okay with)?

Java client parses the stuff in the same way, so the trick should work

**Comment by mykola-mokhnach** [comment]
I merge it for now, but we need to monitor https://github.com/SeleniumHQ/selenium/issues/5562, since there might an issue in the W3C spec itself.

**Comment by mykola-mokhnach** [comment]
@dpgraham Can you please publish base driver, so users can try the fix?

**Pull request merged**
