### PR TITLE
feat: add option to skip app uninstall irrespective of reset type

### PR DESCRIPTION
**Pull request by swaraliRaut**
Adding a new capability "skipAppUninstall" to address https://github.com/appium/appium/issues/14607

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I would rather not add this capability to the base driver as it might not be applicable for inherited drivers. Consider adding it to particular platform drivers instead

**Comment by swaraliRaut** [comment]
@mykola-mokhnach  "skipUninstall" is already initialized in base driver so I thought utilising that might be better than adding a new opt in platform specific drivers. Adding it to platform specific drivers will lead to duplicate changes in multiple drivers too. eg android driver, ios driver etc. Am I missing something here?

**Comment by mykola-mokhnach** [comment]
I am ok with having duplicated caps. It is better than having caps with no use

**Comment by swaraliRaut** [comment]
opts.skipUninstall already exists in base driver and is being used in majority of derived drivers already. All this does is use the cap to drive the value of already present opts.skipUninstall in base driver.

I would really like to understand your perspective here to help me learn for future contributions, so I would appreciate if you can explain the downside of adding the cap to base driver in this case and why is it preferable to add these changes to multiple derived drivers instead.?

**Comment by mykola-mokhnach** [comment]
Everything that is added to the base driver is them automatically exposed to all other depending drivers. Not all of them (actually only some) have the concept of app to uninstall. Also, it is much easier to change/remove that concept from the particular driver rather from the base driver (such change would require bumping of its major version and updating of all depending modules).

**Comment by swaraliRaut** [comment]
oh, I see. thanks for explaining that to me. I will create separate PRs for particular drivers.

**Pull request closed without merging**
