### PR TITLE
added rotation routes

### PR DESCRIPTION
**Pull request by rafael-chavez**
@jlipps @imurchie 

I know this involves changing the hash for the gulp tests. But before thats done want to make sure this pull is ok. 

Here is the spec for this [route](https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#device-orientation)

### CODE REVIEW

**Comment by imurchie** [comment]
The spec seems to say that it should accept a `DeviceRotation` object, but their examples are sending `x`, `y`, and `z` values (https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#devicerotation). Not sure which is to be taken as correct.

**Comment by jlipps** [comment]
`DeviceRotation` is the "name" of the object type, similarly to `NetworkConnection` objects. that name doesn't actually need to show up in the JSONWP though.

**Comment by imurchie** [comment]
Ah. Ok. That needs to be reflected here, then.

**Comment by rafael-chavez** [comment]
Are we saying the post part should change like this?

```
POST: {command: 'setRotation', payloadParams: {required: ['rotation']}}
```
 to :
```
POST: { command: 'setRotation', payloadParams: { unwrap: 'parameters', required: ['type'] } }
```

**Comment by imurchie** [comment]
No. The spec says the payload should be something like

```json
{"name": "rotation", "parameters": {"x": 0, "y": 0, "z": 0}}
```

So in the mjsonwp implementation here, it should be something like

```js
payloadParams: {unwrap: 'parameters', required: ['x', 'y', 'z']}
```

**Comment by rafael-chavez** [comment]
updated mobile spec [here](https://github.com/SeleniumHQ/mobile-spec/pull/5)

**Comment by imurchie** [comment]
Looks good to me.

**Comment by imurchie** [comment]
And thanks for fixing the spec!

**Comment by rafael-chavez** [comment]
@imurchie should i update the expected test hash?

**Comment by imurchie** [comment]
Yes. Otherwise the tests will fail and we can't merge.

**Comment by imurchie** [comment]
Thanks!

**Pull request merged**
